version: "1"

services:
  backend:
    build:
      context: .
      dockerfile: backend_dockerfile
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./backend/data
        target: /app/data
    
